//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumption
    {
        public int ConsumptionID { get; set; }
        public Nullable<int> MealID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Product Product { get; set; }
    }
}
