//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCalculator.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Consumptions = new HashSet<Consumption>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductName2 { get; set; }
        public int Calories { get; set; }
        public Nullable<int> Protein { get; set; }
        public Nullable<int> Fat { get; set; }
        public Nullable<int> Carbohydrates { get; set; }
        public Nullable<int> Sugar { get; set; }
        public Nullable<int> Salt { get; set; }
        public Nullable<int> Fiber { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumption> Consumptions { get; set; }
    }
}
